// Generated by scripts/gen-lucide-icons from Lucide (https://lucide.dev, ISC licence). Do not edit.
package com.c0mpile.grimmreader.core.designsystem.icon

import androidx.compose.ui.graphics.vector.ImageVector

@Suppress("MaxLineLength")
object LucideIcons {
    val ArrowLeft: ImageVector by lazy {
        lucide("arrow-left") {
            stroke("m12 19-7-7 7-7")
            stroke("M19 12H5")
        }
    }
    val ArrowUpDown: ImageVector by lazy {
        lucide("arrow-up-down") {
            stroke("m21 16-4 4-4-4")
            stroke("M17 20V4")
            stroke("m3 8 4-4 4 4")
            stroke("M7 4v16")
        }
    }
    val BookBookmark: ImageVector by lazy {
        lucide("book-bookmark") {
            stroke("M10 2v7.751a.25.25 0 00.407.195l2.28-1.834a.5.5 0 01.627 0l2.28 1.834A.25.25 0 0016 9.751V2")
            stroke("M4 19.5v-15A2.5 2.5 0 016.5 2H19a1 1 0 011 1v18a1 1 0 01-1 1H6.5a1 1 0 010-5H20")
        }
    }
    val BookCopy: ImageVector by lazy {
        lucide("book-copy") {
            stroke("M5 7a2 2 0 0 0-2 2v11")
            stroke("M5.803 18H5a2 2 0 0 0 0 4h9.5a.5.5 0 0 0 .5-.5V21")
            stroke("M9 15V4a2 2 0 0 1 2-2h9.5a.5.5 0 0 1 .5.5v14a.5.5 0 0 1-.5.5H11a2 2 0 0 1 0-4h10")
        }
    }
    val BookOpen: ImageVector by lazy {
        lucide("book-open") {
            stroke("M12 5v16")
            stroke(
                "M20.001 19A2 2 0 0022 17V5a2 2 0 00-1.999-2L16 3.002A5 5 0 0012 5a5 5 0 00-4-2H4a2 2 0 00-2 2v12a2 2 0 001.999 2H8a5 5 0 014 2 5 5 0 014-2z",
            )
        }
    }
    val Book: ImageVector by lazy {
        lucide("book") {
            stroke("M4 19.5v-15A2.5 2.5 0 0 1 6.5 2H19a1 1 0 0 1 1 1v18a1 1 0 0 1-1 1H6.5a1 1 0 0 1 0-5H20")
        }
    }
    val BookmarkCheck: ImageVector by lazy {
        lucide("bookmark-check") {
            stroke("M17 3a2 2 0 0 1 2 2v15a1 1 0 0 1-1.496.868l-4.512-2.578a2 2 0 0 0-1.984 0l-4.512 2.578A1 1 0 0 1 5 20V5a2 2 0 0 1 2-2z")
            stroke("m9 10 2 2 4-4")
        }
    }
    val Bookmark: ImageVector by lazy {
        lucide("bookmark") {
            stroke("M17 3a2 2 0 0 1 2 2v15a1 1 0 0 1-1.496.868l-4.512-2.578a2 2 0 0 0-1.984 0l-4.512 2.578A1 1 0 0 1 5 20V5a2 2 0 0 1 2-2z")
        }
    }
    val Check: ImageVector by lazy {
        lucide("check") {
            stroke("M20 6 9 17l-5-5")
        }
    }
    val ChevronDown: ImageVector by lazy {
        lucide("chevron-down") {
            stroke("m6 9 6 6 6-6")
        }
    }
    val ChevronLeft: ImageVector by lazy {
        lucide("chevron-left") {
            stroke("m15 18-6-6 6-6")
        }
    }
    val ChevronRight: ImageVector by lazy {
        lucide("chevron-right") {
            stroke("m9 18 6-6-6-6")
        }
    }
    val CircleAlert: ImageVector by lazy {
        lucide("circle-alert") {
            stroke("M2.0 12.0a10.0 10.0 0 1 0 20.0 0a10.0 10.0 0 1 0 -20.0 0z")
            stroke("M12 8L12 12")
            stroke("M12 16L12.01 16")
        }
    }
    val CloudOff: ImageVector by lazy {
        lucide("cloud-off") {
            stroke("M10.94 5.274A7 7 0 0 1 15.71 10h1.79a4.5 4.5 0 0 1 4.222 6.057")
            stroke("M18.796 18.81A4.5 4.5 0 0 1 17.5 19H9A7 7 0 0 1 5.79 5.78")
            stroke("m2 2 20 20")
        }
    }
    val Download: ImageVector by lazy {
        lucide("download") {
            stroke("M12 15V3")
            stroke("M21 15v4a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2v-4")
            stroke("m7 10 5 5 5-5")
        }
    }
    val Eye: ImageVector by lazy {
        lucide("eye") {
            stroke("M2.062 12.348a1 1 0 0 1 0-.696 10.75 10.75 0 0 1 19.876 0 1 1 0 0 1 0 .696 10.75 10.75 0 0 1-19.876 0")
            stroke("M9.0 12.0a3.0 3.0 0 1 0 6.0 0a3.0 3.0 0 1 0 -6.0 0z")
        }
    }
    val FileText: ImageVector by lazy {
        lucide("file-text") {
            stroke("M6 22a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h8a2.4 2.4 0 0 1 1.704.706l3.588 3.588A2.4 2.4 0 0 1 20 8v12a2 2 0 0 1-2 2z")
            stroke("M14 2v5a1 1 0 0 0 1 1h5")
            stroke("M10 9H8")
            stroke("M16 13H8")
            stroke("M16 17H8")
        }
    }
    val FolderOpen: ImageVector by lazy {
        lucide("folder-open") {
            stroke(
                "m6 14 1.5-2.9A2 2 0 0 1 9.24 10H20a2 2 0 0 1 1.94 2.5l-1.54 6a2 2 0 0 1-1.95 1.5H4a2 2 0 0 1-2-2V5a2 2 0 0 1 2-2h3.9a2 2 0 0 1 1.69.9l.81 1.2a2 2 0 0 0 1.67.9H18a2 2 0 0 1 2 2v2",
            )
        }
    }
    val Globe: ImageVector by lazy {
        lucide("globe") {
            stroke("M2.0 12.0a10.0 10.0 0 1 0 20.0 0a10.0 10.0 0 1 0 -20.0 0z")
            stroke("M12 2a14.5 14.5 0 0 0 0 20 14.5 14.5 0 0 0 0-20")
            stroke("M2 12h20")
        }
    }
    val Heart: ImageVector by lazy {
        lucide("heart") {
            stroke(
                "M2 9.5a5.5 5.5 0 0 1 9.591-3.676.56.56 0 0 0 .818 0A5.49 5.49 0 0 1 22 9.5c0 2.29-1.5 4-3 5.5l-5.492 5.313a2 2 0 0 1-3 .019L5 15c-1.5-1.5-3-3.2-3-5.5",
            )
        }
    }
    val House: ImageVector by lazy {
        lucide("house") {
            stroke("M15 21v-8a1 1 0 0 0-1-1h-4a1 1 0 0 0-1 1v8")
            stroke("M3 10a2 2 0 0 1 .709-1.528l7-6a2 2 0 0 1 2.582 0l7 6A2 2 0 0 1 21 10v9a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2z")
        }
    }
    val Inbox: ImageVector by lazy {
        lucide("inbox") {
            stroke("M22 12L16 12L14 15L10 15L8 12L2 12")
            stroke("M5.45 5.11 2 12v6a2 2 0 0 0 2 2h16a2 2 0 0 0 2-2v-6l-3.45-6.89A2 2 0 0 0 16.76 4H7.24a2 2 0 0 0-1.79 1.11z")
        }
    }
    val LayoutGrid: ImageVector by lazy {
        lucide("layout-grid") {
            stroke(
                "M4.0 3.0h5.0a1.0 1.0 0 0 1 1.0 1.0v5.0a1.0 1.0 0 0 1 -1.0 1.0h-5.0a1.0 1.0 0 0 1 -1.0 -1.0v-5.0a1.0 1.0 0 0 1 1.0 -1.0z",
            )
            stroke(
                "M15.0 3.0h5.0a1.0 1.0 0 0 1 1.0 1.0v5.0a1.0 1.0 0 0 1 -1.0 1.0h-5.0a1.0 1.0 0 0 1 -1.0 -1.0v-5.0a1.0 1.0 0 0 1 1.0 -1.0z",
            )
            stroke(
                "M15.0 14.0h5.0a1.0 1.0 0 0 1 1.0 1.0v5.0a1.0 1.0 0 0 1 -1.0 1.0h-5.0a1.0 1.0 0 0 1 -1.0 -1.0v-5.0a1.0 1.0 0 0 1 1.0 -1.0z",
            )
            stroke(
                "M4.0 14.0h5.0a1.0 1.0 0 0 1 1.0 1.0v5.0a1.0 1.0 0 0 1 -1.0 1.0h-5.0a1.0 1.0 0 0 1 -1.0 -1.0v-5.0a1.0 1.0 0 0 1 1.0 -1.0z",
            )
        }
    }
    val LibraryBig: ImageVector by lazy {
        lucide("library-big") {
            stroke(
                "M4.0 3.0h6.0a1.0 1.0 0 0 1 1.0 1.0v16.0a1.0 1.0 0 0 1 -1.0 1.0h-6.0a1.0 1.0 0 0 1 -1.0 -1.0v-16.0a1.0 1.0 0 0 1 1.0 -1.0z",
            )
            stroke("M7 3v18")
            stroke("M20.4 18.9c.2.5-.1 1.1-.6 1.3l-1.9.7c-.5.2-1.1-.1-1.3-.6L11.1 5.1c-.2-.5.1-1.1.6-1.3l1.9-.7c.5-.2 1.1.1 1.3.6Z")
        }
    }
    val Library: ImageVector by lazy {
        lucide("library") {
            stroke("m16 6 4 14")
            stroke("M12 6v14")
            stroke("M8 8v12")
            stroke("M4 4v16")
        }
    }
    val List: ImageVector by lazy {
        lucide("list") {
            stroke("M3 5h.01")
            stroke("M3 12h.01")
            stroke("M3 19h.01")
            stroke("M8 5h13")
            stroke("M8 12h13")
            stroke("M8 19h13")
        }
    }
    val LogOut: ImageVector by lazy {
        lucide("log-out") {
            stroke("m16 17 5-5-5-5")
            stroke("M21 12H9")
            stroke("M9 21H5a2 2 0 0 1-2-2V5a2 2 0 0 1 2-2h4")
        }
    }
    val Maximize: ImageVector by lazy {
        lucide("maximize") {
            stroke("M8 3H5a2 2 0 0 0-2 2v3")
            stroke("M21 8V5a2 2 0 0 0-2-2h-3")
            stroke("M3 16v3a2 2 0 0 0 2 2h3")
            stroke("M16 21h3a2 2 0 0 0 2-2v-3")
        }
    }
    val Menu: ImageVector by lazy {
        lucide("menu") {
            stroke("M4 5h16")
            stroke("M4 12h16")
            stroke("M4 19h16")
        }
    }
    val Minimize: ImageVector by lazy {
        lucide("minimize") {
            stroke("M8 3v3a2 2 0 0 1-2 2H3")
            stroke("M21 8h-3a2 2 0 0 1-2-2V3")
            stroke("M3 16h3a2 2 0 0 1 2 2v3")
            stroke("M16 21v-3a2 2 0 0 1 2-2h3")
        }
    }
    val Minus: ImageVector by lazy {
        lucide("minus") {
            stroke("M5 12h14")
        }
    }
    val Moon: ImageVector by lazy {
        lucide("moon") {
            stroke("M20.985 12.486a9 9 0 1 1-9.473-9.472c.405-.022.617.46.402.803a6 6 0 0 0 8.268 8.268c.344-.215.825-.004.803.401")
        }
    }
    val NotebookPen: ImageVector by lazy {
        lucide("notebook-pen") {
            stroke("M13.4 2H6a2 2 0 0 0-2 2v16a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2v-7.4")
            stroke("M2 6h4")
            stroke("M2 10h4")
            stroke("M2 14h4")
            stroke("M2 18h4")
            stroke(
                "M21.378 5.626a1 1 0 1 0-3.004-3.004l-5.01 5.012a2 2 0 0 0-.506.854l-.837 2.87a.5.5 0 0 0 .62.62l2.87-.837a2 2 0 0 0 .854-.506z",
            )
        }
    }
    val PanelLeftClose: ImageVector by lazy {
        lucide("panel-left-close") {
            stroke(
                "M5.0 3.0h14.0a2.0 2.0 0 0 1 2.0 2.0v14.0a2.0 2.0 0 0 1 -2.0 2.0h-14.0a2.0 2.0 0 0 1 -2.0 -2.0v-14.0a2.0 2.0 0 0 1 2.0 -2.0z",
            )
            stroke("M9 3v18")
            stroke("m16 15-3-3 3-3")
        }
    }
    val PenLine: ImageVector by lazy {
        lucide("pen-line") {
            stroke("M13 21h8")
            stroke(
                "M21.174 6.812a1 1 0 0 0-3.986-3.987L3.842 16.174a2 2 0 0 0-.5.83l-1.321 4.352a.5.5 0 0 0 .623.622l4.353-1.32a2 2 0 0 0 .83-.497z",
            )
        }
    }
    val Plus: ImageVector by lazy {
        lucide("plus") {
            stroke("M5 12h14")
            stroke("M12 5v14")
        }
    }
    val RefreshCw: ImageVector by lazy {
        lucide("refresh-cw") {
            stroke("M3 12a9 9 0 0 1 9-9 9.75 9.75 0 0 1 6.74 2.74L21 8")
            stroke("M21 3v5h-5")
            stroke("M21 12a9 9 0 0 1-9 9 9.75 9.75 0 0 1-6.74-2.74L3 16")
            stroke("M8 16H3v5")
        }
    }
    val Search: ImageVector by lazy {
        lucide("search") {
            stroke("m21 21-4.34-4.34")
            stroke("M3.0 11.0a8.0 8.0 0 1 0 16.0 0a8.0 8.0 0 1 0 -16.0 0z")
        }
    }
    val Server: ImageVector by lazy {
        lucide("server") {
            stroke(
                "M4.0 2.0h16.0a2.0 2.0 0 0 1 2.0 2.0v4.0a2.0 2.0 0 0 1 -2.0 2.0h-16.0a2.0 2.0 0 0 1 -2.0 -2.0v-4.0a2.0 2.0 0 0 1 2.0 -2.0z",
            )
            stroke(
                "M4.0 14.0h16.0a2.0 2.0 0 0 1 2.0 2.0v4.0a2.0 2.0 0 0 1 -2.0 2.0h-16.0a2.0 2.0 0 0 1 -2.0 -2.0v-4.0a2.0 2.0 0 0 1 2.0 -2.0z",
            )
            stroke("M6 6L6.01 6")
            stroke("M6 18L6.01 18")
        }
    }
    val Settings: ImageVector by lazy {
        lucide("settings") {
            stroke(
                "M9.671 4.136a2.34 2.34 0 0 1 4.659 0 2.34 2.34 0 0 0 3.319 1.915 2.34 2.34 0 0 1 2.33 4.033 2.34 2.34 0 0 0 0 3.831 2.34 2.34 0 0 1-2.33 4.033 2.34 2.34 0 0 0-3.319 1.915 2.34 2.34 0 0 1-4.659 0 2.34 2.34 0 0 0-3.32-1.915 2.34 2.34 0 0 1-2.33-4.033 2.34 2.34 0 0 0 0-3.831A2.34 2.34 0 0 1 6.35 6.051a2.34 2.34 0 0 0 3.319-1.915",
            )
            stroke("M9.0 12.0a3.0 3.0 0 1 0 6.0 0a3.0 3.0 0 1 0 -6.0 0z")
        }
    }
    val Smartphone: ImageVector by lazy {
        lucide("smartphone") {
            stroke(
                "M7.0 2.0h10.0a2.0 2.0 0 0 1 2.0 2.0v16.0a2.0 2.0 0 0 1 -2.0 2.0h-10.0a2.0 2.0 0 0 1 -2.0 -2.0v-16.0a2.0 2.0 0 0 1 2.0 -2.0z",
            )
            stroke("M12 18h.01")
        }
    }
    val Sparkles: ImageVector by lazy {
        lucide("sparkles") {
            stroke(
                "M11.017 2.814a1 1 0 0 1 1.966 0l1.051 5.558a2 2 0 0 0 1.594 1.594l5.558 1.051a1 1 0 0 1 0 1.966l-5.558 1.051a2 2 0 0 0-1.594 1.594l-1.051 5.558a1 1 0 0 1-1.966 0l-1.051-5.558a2 2 0 0 0-1.594-1.594l-5.558-1.051a1 1 0 0 1 0-1.966l5.558-1.051a2 2 0 0 0 1.594-1.594z",
            )
            stroke("M20 2v4")
            stroke("M22 4h-4")
            stroke("M2.0 20.0a2.0 2.0 0 1 0 4.0 0a2.0 2.0 0 1 0 -4.0 0z")
        }
    }
    val Sun: ImageVector by lazy {
        lucide("sun") {
            stroke("M8.0 12.0a4.0 4.0 0 1 0 8.0 0a4.0 4.0 0 1 0 -8.0 0z")
            stroke("M12 2v2")
            stroke("M12 20v2")
            stroke("m4.93 4.93 1.41 1.41")
            stroke("m17.66 17.66 1.41 1.41")
            stroke("M2 12h2")
            stroke("M20 12h2")
            stroke("m6.34 17.66-1.41 1.41")
            stroke("m19.07 4.93-1.41 1.41")
        }
    }
    val Trash: ImageVector by lazy {
        lucide("trash") {
            stroke("M10 11v6")
            stroke("M14 11v6")
            stroke("M19 6v14a2 2 0 0 1-2 2H7a2 2 0 0 1-2-2V6")
            stroke("M3 6h18")
            stroke("M8 6V4a2 2 0 0 1 2-2h4a2 2 0 0 1 2 2v2")
        }
    }
    val User: ImageVector by lazy {
        lucide("user") {
            stroke("M19 21v-2a4 4 0 0 0-4-4H9a4 4 0 0 0-4 4v2")
            stroke("M8.0 7.0a4.0 4.0 0 1 0 8.0 0a4.0 4.0 0 1 0 -8.0 0z")
        }
    }
    val Users: ImageVector by lazy {
        lucide("users") {
            stroke("M16 21v-2a4 4 0 0 0-4-4H6a4 4 0 0 0-4 4v2")
            stroke("M16 3.128a4 4 0 0 1 0 7.744")
            stroke("M22 21v-2a4 4 0 0 0-3-3.87")
            stroke("M5.0 7.0a4.0 4.0 0 1 0 8.0 0a4.0 4.0 0 1 0 -8.0 0z")
        }
    }
    val WifiOff: ImageVector by lazy {
        lucide("wifi-off") {
            stroke("M12 20h.01")
            stroke("M8.5 16.429a5 5 0 0 1 7 0")
            stroke("M5 12.859a10 10 0 0 1 5.17-2.69")
            stroke("M19 12.859a10 10 0 0 0-2.007-1.523")
            stroke("M2 8.82a15 15 0 0 1 4.177-2.643")
            stroke("M22 8.82a15 15 0 0 0-11.288-3.764")
            stroke("m2 2 20 20")
        }
    }
    val X: ImageVector by lazy {
        lucide("x") {
            stroke("M18 6 6 18")
            stroke("m6 6 12 12")
        }
    }
}
