// Generated by scripts/gen-lucide-icons from Lucide (https://lucide.dev, ISC licence). Do not edit.
package com.c0mpile.grimmreader.core.designsystem.icon

import androidx.compose.ui.graphics.vector.ImageVector

@Suppress("MaxLineLength")
object LucideIcons {
    val ArrowLeft: ImageVector by lazy {
        lucide("arrow-left") {
            stroke("m12 19-7-7 7-7")
            stroke("M19 12H5")
        }
    }
    val BookOpen: ImageVector by lazy {
        lucide("book-open") {
            stroke("M12 5v16")
            stroke(
                "M20.001 19A2 2 0 0022 17V5a2 2 0 00-1.999-2L16 3.002A5 5 0 0012 5a5 5 0 00-4-2H4a2 2 0 00-2 2v12a2 2 0 001.999 2H8a5 5 0 014 2 5 5 0 014-2z",
            )
        }
    }
    val Check: ImageVector by lazy {
        lucide("check") {
            stroke("M20 6 9 17l-5-5")
        }
    }
    val ChevronRight: ImageVector by lazy {
        lucide("chevron-right") {
            stroke("m9 18 6-6-6-6")
        }
    }
    val CircleAlert: ImageVector by lazy {
        lucide("circle-alert") {
            stroke("M2.0 12.0a10.0 10.0 0 1 0 20.0 0a10.0 10.0 0 1 0 -20.0 0z")
            stroke("M12 8L12 12")
            stroke("M12 16L12.01 16")
        }
    }
    val CloudOff: ImageVector by lazy {
        lucide("cloud-off") {
            stroke("M10.94 5.274A7 7 0 0 1 15.71 10h1.79a4.5 4.5 0 0 1 4.222 6.057")
            stroke("M18.796 18.81A4.5 4.5 0 0 1 17.5 19H9A7 7 0 0 1 5.79 5.78")
            stroke("m2 2 20 20")
        }
    }
    val Download: ImageVector by lazy {
        lucide("download") {
            stroke("M12 15V3")
            stroke("M21 15v4a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2v-4")
            stroke("m7 10 5 5 5-5")
        }
    }
    val Eye: ImageVector by lazy {
        lucide("eye") {
            stroke("M2.062 12.348a1 1 0 0 1 0-.696 10.75 10.75 0 0 1 19.876 0 1 1 0 0 1 0 .696 10.75 10.75 0 0 1-19.876 0")
            stroke("M9.0 12.0a3.0 3.0 0 1 0 6.0 0a3.0 3.0 0 1 0 -6.0 0z")
        }
    }
    val FolderOpen: ImageVector by lazy {
        lucide("folder-open") {
            stroke(
                "m6 14 1.5-2.9A2 2 0 0 1 9.24 10H20a2 2 0 0 1 1.94 2.5l-1.54 6a2 2 0 0 1-1.95 1.5H4a2 2 0 0 1-2-2V5a2 2 0 0 1 2-2h3.9a2 2 0 0 1 1.69.9l.81 1.2a2 2 0 0 0 1.67.9H18a2 2 0 0 1 2 2v2",
            )
        }
    }
    val House: ImageVector by lazy {
        lucide("house") {
            stroke("M15 21v-8a1 1 0 0 0-1-1h-4a1 1 0 0 0-1 1v8")
            stroke("M3 10a2 2 0 0 1 .709-1.528l7-6a2 2 0 0 1 2.582 0l7 6A2 2 0 0 1 21 10v9a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2z")
        }
    }
    val LibraryBig: ImageVector by lazy {
        lucide("library-big") {
            stroke(
                "M4.0 3.0h6.0a1.0 1.0 0 0 1 1.0 1.0v16.0a1.0 1.0 0 0 1 -1.0 1.0h-6.0a1.0 1.0 0 0 1 -1.0 -1.0v-16.0a1.0 1.0 0 0 1 1.0 -1.0z",
            )
            stroke("M7 3v18")
            stroke("M20.4 18.9c.2.5-.1 1.1-.6 1.3l-1.9.7c-.5.2-1.1-.1-1.3-.6L11.1 5.1c-.2-.5.1-1.1.6-1.3l1.9-.7c.5-.2 1.1.1 1.3.6Z")
        }
    }
    val LogOut: ImageVector by lazy {
        lucide("log-out") {
            stroke("m16 17 5-5-5-5")
            stroke("M21 12H9")
            stroke("M9 21H5a2 2 0 0 1-2-2V5a2 2 0 0 1 2-2h4")
        }
    }
    val RefreshCw: ImageVector by lazy {
        lucide("refresh-cw") {
            stroke("M3 12a9 9 0 0 1 9-9 9.75 9.75 0 0 1 6.74 2.74L21 8")
            stroke("M21 3v5h-5")
            stroke("M21 12a9 9 0 0 1-9 9 9.75 9.75 0 0 1-6.74-2.74L3 16")
            stroke("M8 16H3v5")
        }
    }
    val Search: ImageVector by lazy {
        lucide("search") {
            stroke("m21 21-4.34-4.34")
            stroke("M3.0 11.0a8.0 8.0 0 1 0 16.0 0a8.0 8.0 0 1 0 -16.0 0z")
        }
    }
    val Server: ImageVector by lazy {
        lucide("server") {
            stroke(
                "M4.0 2.0h16.0a2.0 2.0 0 0 1 2.0 2.0v4.0a2.0 2.0 0 0 1 -2.0 2.0h-16.0a2.0 2.0 0 0 1 -2.0 -2.0v-4.0a2.0 2.0 0 0 1 2.0 -2.0z",
            )
            stroke(
                "M4.0 14.0h16.0a2.0 2.0 0 0 1 2.0 2.0v4.0a2.0 2.0 0 0 1 -2.0 2.0h-16.0a2.0 2.0 0 0 1 -2.0 -2.0v-4.0a2.0 2.0 0 0 1 2.0 -2.0z",
            )
            stroke("M6 6L6.01 6")
            stroke("M6 18L6.01 18")
        }
    }
    val Settings: ImageVector by lazy {
        lucide("settings") {
            stroke(
                "M9.671 4.136a2.34 2.34 0 0 1 4.659 0 2.34 2.34 0 0 0 3.319 1.915 2.34 2.34 0 0 1 2.33 4.033 2.34 2.34 0 0 0 0 3.831 2.34 2.34 0 0 1-2.33 4.033 2.34 2.34 0 0 0-3.319 1.915 2.34 2.34 0 0 1-4.659 0 2.34 2.34 0 0 0-3.32-1.915 2.34 2.34 0 0 1-2.33-4.033 2.34 2.34 0 0 0 0-3.831A2.34 2.34 0 0 1 6.35 6.051a2.34 2.34 0 0 0 3.319-1.915",
            )
            stroke("M9.0 12.0a3.0 3.0 0 1 0 6.0 0a3.0 3.0 0 1 0 -6.0 0z")
        }
    }
    val Trash: ImageVector by lazy {
        lucide("trash") {
            stroke("M10 11v6")
            stroke("M14 11v6")
            stroke("M19 6v14a2 2 0 0 1-2 2H7a2 2 0 0 1-2-2V6")
            stroke("M3 6h18")
            stroke("M8 6V4a2 2 0 0 1 2-2h4a2 2 0 0 1 2 2v2")
        }
    }
    val WifiOff: ImageVector by lazy {
        lucide("wifi-off") {
            stroke("M12 20h.01")
            stroke("M8.5 16.429a5 5 0 0 1 7 0")
            stroke("M5 12.859a10 10 0 0 1 5.17-2.69")
            stroke("M19 12.859a10 10 0 0 0-2.007-1.523")
            stroke("M2 8.82a15 15 0 0 1 4.177-2.643")
            stroke("M22 8.82a15 15 0 0 0-11.288-3.764")
            stroke("m2 2 20 20")
        }
    }
    val X: ImageVector by lazy {
        lucide("x") {
            stroke("M18 6 6 18")
            stroke("m6 6 12 12")
        }
    }
}
